# Generated by Django 5.0 on 2024-01-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_due_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='code',
            field=models.CharField(max_length=250, verbose_name='Код задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_months',
            field=models.IntegerField(blank=True, null=True, verbose_name='Месяцев до повтора задачи'),
        ),
    ]
