# Generated by Django 5.0 on 2024-01-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_code_alter_task_due_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cw',
            name='next_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Следующее выполнение'),
        ),
    ]
