# Generated by Django 5.0.1 on 2024-01-05 16:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_cw_perform_date_gt_today_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cw',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='cw',
            name='next_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Next due date'),
        ),
        migrations.AlterField(
            model_name='cw',
            name='perform_date',
            field=models.DateField(verbose_name='Perform date'),
        ),
        migrations.AlterField(
            model_name='cw',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliances', to='tasks.task', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='cw',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Changed'),
        ),
        migrations.AlterField(
            model_name='task',
            name='code',
            field=models.CharField(max_length=250, verbose_name='Task code'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_months',
            field=models.IntegerField(blank=True, null=True, verbose_name='Due months'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Changed'),
        ),
    ]
