# Generated by Django 5.0 on 2024-01-08 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_cw_perform_date_gt_today_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cw',
            name='perform_date_gt_today',
        ),
        migrations.AddConstraint(
            model_name='cw',
            constraint=models.CheckConstraint(check=models.Q(('perform_date__lte', datetime.date(2024, 1, 8))), name='perform_date_lte_today'),
        ),
    ]
