# Generated by Django 5.0.1 on 2024-01-09 15:12

import apps.tasks.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_cw_perform_date_lte_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cw',
            name='perform_date',
            field=models.DateField(validators=[apps.tasks.services.validate_cw_perf_date], verbose_name='Perform date'),
        ),
    ]
