# Generated by Django 5.0.1 on 2024-01-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_cw_perform_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cw',
            name='perform_date',
            field=models.DateField(verbose_name='Perform date'),
        ),
    ]
