# Generated by Django 5.0.1 on 2024-01-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_cw_perform_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='next_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Next due date'),
        ),
    ]
