# Generated by Django 5.0.1 on 2024-01-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_task_next_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='next_due_date',
        ),
    ]
