# Generated by Django 5.0.1 on 2024-01-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_tolerance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolerance',
            name='percent_count',
            field=models.BooleanField(default=False, verbose_name='Counted in percents'),
        ),
        migrations.AlterField(
            model_name='tolerance',
            name='adj_unit',
            field=models.CharField(choices=[('M', 'Months'), ('D', 'Days')], max_length=1, verbose_name='Adj type'),
        ),
    ]
