# Generated by Django 5.0.1 on 2024-01-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_tolerance_percent_count_alter_tolerance_adj_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tolerance',
            name='adj_unit',
        ),
        migrations.RemoveField(
            model_name='tolerance',
            name='neg_adj',
        ),
        migrations.RemoveField(
            model_name='tolerance',
            name='percent_count',
        ),
        migrations.RemoveField(
            model_name='tolerance',
            name='pos_adj',
        ),
        migrations.AddField(
            model_name='tolerance',
            name='neg_tol',
            field=models.FloatField(blank=True, null=True, verbose_name='Negative_adj'),
        ),
        migrations.AddField(
            model_name='tolerance',
            name='pos_tol',
            field=models.FloatField(blank=True, null=True, verbose_name='Positive adj'),
        ),
        migrations.AddField(
            model_name='tolerance',
            name='tol_type',
            field=models.CharField(choices=[('M', 'Months'), ('D', 'Days'), ('P', 'Percents')], default='M', max_length=1, verbose_name='Tolerance type'),
        ),
    ]
