# Generated by Django 5.0.1 on 2024-01-18 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_remove_tolerance_adj_unit_remove_tolerance_neg_adj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cw',
            name='adjusted_days',
            field=models.IntegerField(default=0, verbose_name='Adjustment'),
        ),
        migrations.AlterField(
            model_name='tolerance',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolerance', to='tasks.task'),
        ),
    ]
