# Generated by Django 5.0.1 on 2024-01-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_alter_tolerance_neg_tol_alter_tolerance_pos_tol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolerance',
            name='neg_tol',
            field=models.FloatField(blank=True, null=True, verbose_name='Negative_adj'),
        ),
        migrations.AlterField(
            model_name='tolerance',
            name='pos_tol',
            field=models.FloatField(blank=True, null=True, verbose_name='Positive adj'),
        ),
    ]
