# Generated by Django 5.0.1 on 2024-01-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_alter_tolerance_neg_tol_alter_tolerance_pos_tol'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolerance',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active_tolerance'),
        ),
        migrations.AlterUniqueTogether(
            name='tolerance',
            unique_together={('task', 'is_active')},
        ),
    ]
