# Generated by Django 5.0.1 on 2024-01-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_tolerance_is_active_alter_tolerance_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tolerance',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='tolerance',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('task', 'is_active'), name='unique_active_tolerance_for_task'),
        ),
    ]
