# Generated by Django 5.0.1 on 2024-01-22 07:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_alter_tolerance_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Changed')),
                ('pos_tol_mos', models.FloatField(blank=True, null=True, verbose_name='MOS positive')),
                ('neg_tol_mos', models.FloatField(blank=True, null=True, verbose_name='MOS negative')),
                ('mos_unit', models.CharField(choices=[('M', 'Months'), ('D', 'Days'), ('P', 'Percents')], default='M', max_length=1, verbose_name='MOS unit')),
                ('is_active', models.BooleanField(default=False, verbose_name='active_tolerance')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='tasks.task')),
            ],
        ),
        migrations.DeleteModel(
            name='Tolerance',
        ),
        migrations.AddConstraint(
            model_name='requirements',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('task', 'is_active'), name='unique_active_tolerance_for_task'),
        ),
    ]
