# Generated by Django 5.0.1 on 2024-01-23 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_requirements_delete_tolerance_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='requirements',
            name='unique_active_tolerance_for_task',
        ),
        migrations.RemoveField(
            model_name='cw',
            name='adjusted_days',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='mos_unit',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='neg_tol_mos',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='pos_tol_mos',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_months',
        ),
        migrations.AddField(
            model_name='cw',
            name='adj_mos',
            field=models.IntegerField(default=0, verbose_name='Adjustment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requirements',
            name='due_months',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Due_months'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='due_months_unit',
            field=models.CharField(choices=[('M', 'Months'), ('D', 'Days')], default="M", max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requirements',
            name='tol_mos_unit',
            field=models.CharField(choices=[('M', 'Months'), ('D', 'Days'), ('P', 'Percents')], default='M', max_length=1, verbose_name='MOS unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requirements',
            name='tol_neg_mos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='MOS negative'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='tol_pos_mos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='MOS positive'),
        ),
    ]
