# Generated by Django 5.0.1 on 2024-01-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_requirements_delete_tolerance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_months',
        ),
        migrations.AddField(
            model_name='requirements',
            name='due_months',
            field=models.IntegerField(blank=True, null=True, verbose_name='Due months'),
        ),
    ]
