# Generated by Django 5.0.1 on 2024-01-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_remove_task_due_months_requirements_due_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='mos_unit',
            field=models.CharField(choices=[('M', 'Months'), ('D', 'Days'), ('P', 'Percents')], default=[('M', 'Months'), ('D', 'Days'), ('P', 'Percents')], max_length=1, verbose_name='MOS unit'),
        ),
    ]
