# Generated by Django 5.0.1 on 2024-01-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_remove_requirements_unique_active_tolerance_for_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='is_active',
            field=models.BooleanField(verbose_name='active_tolerance'),
        ),
    ]
