# Generated by Django 5.0.1 on 2024-01-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_alter_requirements_mos_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='hrs_unit',
            field=models.CharField(choices=[('C', 'Cycles'), ('P', 'Percents')], default='M', max_length=1, verbose_name='AFL/ENC unit'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='neg_tol_afl',
            field=models.FloatField(blank=True, null=True, verbose_name='AFL/ENC negative'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='neg_tol_hrs',
            field=models.FloatField(blank=True, null=True, verbose_name='HRS negative'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='pos_tol_afl',
            field=models.FloatField(blank=True, null=True, verbose_name='AFL/ENC positive'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='pos_tol_hrs',
            field=models.FloatField(blank=True, null=True, verbose_name='HRS positive'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='mos_unit',
            field=models.CharField(choices=[('M', 'Months'), ('D', 'Days'), ('P', 'Percents')], default='M', max_length=1, verbose_name='MOS unit'),
        ),
    ]
