# Generated by Django 5.0.1 on 2024-01-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_alter_requirements_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='tol_mos_unit',
            field=models.CharField(blank=True, choices=[('M', 'Months'), ('D', 'Days'), ('P', 'Percents')], max_length=1, null=True, verbose_name='MOS unit'),
        ),
    ]
