# Generated by Django 5.0.1 on 2024-01-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_alter_requirements_tol_mos_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cw',
            name='adj_mos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Adjustment'),
        ),
    ]
