# Generated by Django 5.0.1 on 2024-01-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_requirements_hrs_unit_requirements_neg_tol_afl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='afl_unit',
            field=models.CharField(choices=[('C', 'Cycles'), ('P', 'Percents')], default='M', max_length=1, verbose_name='AFL/ENC unit'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='hrs_unit',
            field=models.CharField(choices=[('H', 'Hours'), ('P', 'Percents')], default='M', max_length=1, verbose_name='HRS unit'),
        ),
    ]
