# Generated by Django 5.0.1 on 2024-01-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_requirements_afl_unit_alter_requirements_hrs_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='afl_unit',
            field=models.CharField(choices=[('C', 'Cycles'), ('P', 'Percents'), ('E', 'Empty')], default='E', max_length=1, verbose_name='AFL/ENC unit'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='hrs_unit',
            field=models.CharField(choices=[('H', 'Hours'), ('P', 'Percents'), ('E', 'Empty')], default='E', max_length=1, verbose_name='HRS unit'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='mos_unit',
            field=models.CharField(choices=[('M', 'Months'), ('D', 'Days'), ('P', 'Percents'), ('E', 'Empty')], default='E', max_length=1, verbose_name='MOS unit'),
        ),
    ]
