# Generated by Django 5.0.1 on 2024-01-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_alter_cw_adj_mos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='due_months',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Due_months'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='due_months_unit',
            field=models.CharField(blank=True, choices=[('M', 'Months'), ('D', 'Days')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='tol_neg_mos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='MOS negative'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='tol_pos_mos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='MOS positive'),
        ),
    ]
