# Generated by Django 5.0.1 on 2024-01-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_alter_requirements_due_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='due_months',
            field=models.IntegerField(blank=True, null=True, verbose_name='Due_months'),
        ),
    ]
