# Generated by Django 5.0.1 on 2024-01-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_alter_requirements_afl_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='due_cycles',
            field=models.FloatField(blank=True, null=True, verbose_name='Due cycles'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='due_hrs',
            field=models.FloatField(blank=True, null=True, verbose_name='Due hours'),
        ),
    ]
