# Generated by Django 5.0.1 on 2024-01-29 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_alter_requirements_due_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='code',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Task code'),
        ),
    ]
