# Generated by Django 5.0.1 on 2024-01-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_requirements_due_cycles_requirements_due_hrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cw',
            name='next_due_cycles',
            field=models.FloatField(blank=True, null=True, verbose_name='Next due cycles'),
        ),
        migrations.AddField(
            model_name='cw',
            name='next_due_hrs',
            field=models.FloatField(blank=True, null=True, verbose_name='Next due hours'),
        ),
    ]
