# Generated by Django 5.0.1 on 2024-01-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_alter_task_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='due_months',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Due_months'),
        ),
    ]
