# Generated by Django 5.0.1 on 2024-01-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_cw_next_due_cycles_cw_next_due_hrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cw',
            name='perform_cycles',
            field=models.FloatField(default=0, verbose_name='Perform cycles'),
        ),
        migrations.AddField(
            model_name='cw',
            name='perform_hours',
            field=models.FloatField(default=0, verbose_name='Perform hours'),
        ),
    ]
