# Generated by Django 5.0.1 on 2024-02-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_alter_requirements_due_months'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cw',
            unique_together=set(),
        ),
    ]
