# Generated by Django 5.0.1 on 2024-01-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_cw_perform_cycles_cw_perform_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='cw',
            name='adjusted_hrs',
            field=models.FloatField(default=0, verbose_name='Adjustment hrs'),
        ),
        migrations.AlterField(
            model_name='cw',
            name='adjusted_days',
            field=models.IntegerField(default=0, verbose_name='Adjustment mos'),
        ),
    ]
