# Generated by Django 5.0.1 on 2024-02-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_alter_cw_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='due_hrs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Due hrs'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='tol_hrs_unit',
            field=models.CharField(blank=True, choices=[('H', 'Hours'), ('P', 'Percents')], max_length=1, null=True, verbose_name='HRS unit'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='tol_neg_hrs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='HRS negative'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='tol_pos_hrs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='HRS positive'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='due_months_unit',
            field=models.CharField(blank=True, choices=[('M', 'Months'), ('D', 'Days')], max_length=1, null=True, verbose_name='Due months unit'),
        ),
    ]
