# Generated by Django 5.0.1 on 2024-02-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_requirements_due_hrs_requirements_tol_hrs_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cw',
            name='adj_hrs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Adjustment_hours'),
        ),
        migrations.AddField(
            model_name='cw',
            name='next_due_hrs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Next due hrs'),
        ),
        migrations.AlterField(
            model_name='cw',
            name='adj_mos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Adjustment_months'),
        ),
    ]
