# Generated by Django 5.0.1 on 2024-01-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_cw_adjusted_cycles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cw',
            name='perform_hours',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Perform hours'),
        ),
    ]
