# Generated by Django 5.0.1 on 2024-01-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0035_alter_cw_perform_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cw',
            name='perform_cycles',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Perform cycles'),
        ),
    ]
