# Generated by Django 5.0.1 on 2024-02-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0035_cw_adj_hrs_cw_next_due_hrs_alter_cw_adj_mos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cw',
            name='perform_hrs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Perform hours'),
        ),
    ]
