# Generated by Django 5.0.1 on 2024-01-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0036_alter_cw_perform_cycles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='afl_unit',
            field=models.CharField(blank=True, choices=[('C', 'Cycles'), ('P', 'Percents'), ('E', 'Empty')], default='E', max_length=1, null=True, verbose_name='AFL/ENC unit'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='hrs_unit',
            field=models.CharField(blank=True, choices=[('H', 'Hours'), ('P', 'Percents'), ('E', 'Empty')], default='E', max_length=1, null=True, verbose_name='HRS unit'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='mos_unit',
            field=models.CharField(blank=True, choices=[('M', 'Months'), ('D', 'Days'), ('P', 'Percents'), ('E', 'Empty')], default='E', max_length=1, null=True, verbose_name='MOS unit'),
        ),
    ]
