# Generated by Django 5.0.1 on 2024-02-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0037_requirements_due_cyc_requirements_tol_cyc_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cw',
            name='adj_cyc',
            field=models.IntegerField(blank=True, null=True, verbose_name='Adjustment cycles'),
        ),
        migrations.AddField(
            model_name='cw',
            name='next_due_cyc',
            field=models.IntegerField(blank=True, null=True, verbose_name='Next due cycles'),
        ),
        migrations.AddField(
            model_name='cw',
            name='perform_cyc',
            field=models.IntegerField(blank=True, null=True, verbose_name='Perform cycles'),
        ),
    ]
