# Generated by Django 5.0.1 on 2024-02-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0038_cw_adj_cyc_cw_next_due_cyc_cw_perform_cyc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cw',
            name='next_due_cyc',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Next due cycles'),
        ),
        migrations.AlterField(
            model_name='cw',
            name='perform_cyc',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Perform cycles'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='due_cyc',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Due cycles'),
        ),
    ]
